name: Build Windows release
on:
  push:
    branches: [master]
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -U -r build-requirements.txt

      - name: Build
        env:
          GITHUB_OWNER: "${{ github.repository_owner }}"
          GITHUB_REPO: "${{ github.event.repository.name }}"
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        run: python3 build.py --release
